schema_version: 1

context:
  major_minor: "1.4"
  version: "1.4.85"

package:
  name: lighttpd
  version: ${{ version }}

source:
  url: http://download.lighttpd.net/lighttpd/releases-${{ major_minor }}.x/lighttpd-${{ version }}.tar.gz
  sha256: ffb2ab3e3b9e8b0dfadf9a8b2a5c86084afe5cc68ed3cf4d5776c8a7891c58e9

build:
  number: 0
  skip: not linux

requirements:
  build:
    - pkg-config
    - libtool
    - perl  # Needed to run the tests
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - make
    - automake
    - autoconf
    - libtool
    - m4
  host:
    - zlib
    - bzip2
    - pcre
    - pcre2
    - fcgi2
    - krb5
    - openssl
    - libxml2-devel
    - sqlite
    - libuuid
    - mysql
    - gnutls
    - openldap
    - bzip2
    - nettle
    - keyutils
    - lua
    - brotli
    - zstd
    - libdeflate
  run:
    - bzip2
    - pcre2
    - krb5
    - openssl
    - libxml2-devel
    - sqlite
    - libuuid
    - keyutils
    - lua
    - zstd
    - libdeflate

tests:
  - files:
      recipe:
        - lighttpd.conf
    script:
      - lighttpd -h
      - lighttpd -v
      - lighttpd -t -f lighttpd.conf

about:
  license: BSD-3-Clause
  license_file: COPYING
  summary: Light, fast web server
  description: |
    Lighttpd is rapidly redefining the efficiency of a webserver. It is
    designed and optimized for high performance environments. With a small
    memory footprint compared to other web-servers, effective management of
    the cpu-load, and an advanced feature set, lighttpd is the perfect
    solution for every server that is suffering load problems.
  homepage: http://www.lighttpd.net/
  repository: https://github.com/lighttpd
  documentation: http://redmine.lighttpd.net/projects/lighttpd/wiki

extra:
  recipe-maintainers:
    - sdvillal
    - notestaff
    - hobu
